<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>150dbce6-f8ab-4d61-aec5-661518c34139</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestApp.ApiService\TestApp.ApiService.csproj" />
    <ProjectReference Include="..\TestApp.Web\TestApp.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.0" />
  </ItemGroup>

</Project>
